server:
  port: 8086
spring:
  cloud:
    stream:
      bindings:
        output:
          content-type: application/*+avro
          destination: apm-topic
      default:
        consumer:
          useNativeEncoding: true
        producer:
          useNativeEncoding: true
      kafka:
        binder:
          producer-properties:
            bootstrap-servers: "localhost:9092"
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: "http://localhost:8081"
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer