server:
  port: 8086
spring:
  cloud:
    stream:
      bindings:
        output:
          content-type: application/*+avro
          destination: apm-topic
      default:
        consumer:
          useNativeEncoding: true
        producer:
          useNativeEncoding: true
      kafka:
        binder:
          producer-properties:
            bootstrap-servers: localhost:9092
            schema.registry.url: http://localhost:8081
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroSerializer